# Generated by Django 4.2.4 on 2023-08-25 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ID',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('RFIDcode', models.CharField(max_length=200)),
                ('shortCode', models.CharField(max_length=10)),
                ('member', models.BooleanField(default=False)),
                ('inducted', models.BooleanField(default=False)),
            ],
        ),
    ]
