name: Docs

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
       
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 18
      uses: actions/setup-node@v3
      with:
        cache: 'npm'
        working-directory: /frontend
    
    - run: npm ci && npm run build --if-present && npm test
      working-directory: /frontend
      
