name: Docs

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup Node 18
      uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: 'npm'
        
    
    - run: cd /frontend && npm ci && npm run build --if-present && npm test

      
